user:
  avatar_size: 50
  avatar: "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
category:
  max_time:
    minimum: 0
question:
  answers:
    minimum: 4
name_maximum: 50
user:
  roles:
    admin: admin
    normal: normal
