avatar: "https://secure.gravatar.com/avatar/#"
avatar_size: 50
user:
  roles:
    admin: admin
    normal: normal
csv:
  type: .csv
exam_page_size: 5
host: "localhost:3000"
from_mail_default: "from@example.com"
