user:
  avatar_size: 50
  avatar: "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
category:
  exetime:
    minimum: 0
question:
  answers:
    minimum: 4
name_maximum: 50
user:
  roles:
    admin: admin
    normal: normal
exam_page_size: 5
limited_number_of_records: 10
total_max_correct_number: 10
experied_time_del_exam: 168
